### ISSUE TITLE
Implement integration with Siteimprove API

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-siteimprove#1]
The purpose of this app is to build a tight integration between Enonic XP and Siteimprove.

Siteimprove is a tool to analyze your web pages and aid editors with issues like:
* Broken links
* Spelling mistakes
* Code quality
* Accessibility etc etc

Login to siteimprove admin: https://id.siteimprove.com/account/login

Siteimprove has a "black-box" integration called the CMS-plugin. We will use this as inspiration when building our own widget panel and integrating Siteimprove more tightly with Enonic XP. A token was generated (now hardcoded in the sample integration in the app). The purpose of the token is unknown - but is most likely not relevant when using the API.

This repo holds the boostrapping code to get started with siteimprove, and it also embeds the CMS-plugin with hardcoded links to enonic.com/pricing page - so we can use this as a starting point when building our integration.

Useful links:
* API Documentation: https://api.siteimprove.com/v2/documentation#
* Developer portal: http://developer.siteimprove.com/

Sample things we will need the app to do:
* Present a contextual widget in content studio
* List various reports and content from the Siteimprove API
* Provide direct links for users to access siteimprove admin (with current page context)
* Trigger recrawling of pages in siteimprove after publishing etc etc.

We will start softly by proving small parts of the API and concept and move from there!

*Deep linking*
Siteimprove also offers a way to deep-link from the siteimprove admin interface to the CMS, we should also look at how to support this for a two-way interaction.

**Comment by sigdestad** [comment]
I created a user for mikita, did he not get the mail?

**Comment by edloidas** [comment]
@sigdestad Yeah, I did.
