### ISSUE TITLE
Expose content ID as a meta tag 

### ISSUE THREAD

**Issue by rolfrb** [enonic/app-siteimprove#26]
SiteImprove has explained to us that the content ID for each page needs to be exposed as meta tags for proper integration. Would that feature fit into this app?

Here's the explanation we received from SiteImprove: 

> In order to configure CMS Deeplinking, a meta tag needs to be added in your pages sourcecode that specifies the page ID.
> Therefore we request that you add meta tags to all your pages with individual page ID for each page.
> 
> The meta tags should look like this:
>  ```<meta name='pageID' content='15'>```

**Comment by sigdestad** [comment]
I see, we were note aware of this, so it was not done initially, but should be quite easy to fix.
