### ISSUE TITLE
Don't limit hits when requesting pages

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-siteimprove#29]
<img width="1648" alt="screen shot 2019-01-29 at 15 43 28" src="https://user-images.githubusercontent.com/702065/51916053-c9630d80-23dc-11e9-9405-25a764db0099.png">

The link is indexed in siteimprove.

**Comment by alansemenov** [comment]
@edloidas By default when ``page_size``parameter of the _content/pages_ request is not specified, it's set to **10**, which means that we never get more than 10 pages in the response now. Send ``page_size=1000`` to fetch all the pages.

**Comment by mortyeriksen** [comment]
@alansemenov Does this mean we can't fetch a single url? Is it possible to do this fix soon?
