### ISSUE TITLE
Pageid not added injected after 7.0 upgrade

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-siteimprove#36]
Should have been injected to head.

**Comment by alansemenov** [comment]
Fixed and released version 1.4.1 (upgraded on prod server)

**Comment by mortyeriksen** [comment]
Nå kommer ID, men får fortsatt stack trace. Ny url?
https://enonic.com/admin/tool/com.enonic.xp.app.contentstudio/main#/edit/b5c145d1-353c-43c5-85fb-35d02cbf7d89

(skal vel ikke få stack trace egentlig, den skal vel skjules)
