### ISSUE TITLE
Sites within a folder does not work in the SiteImprove app

### ISSUE THREAD

**Issue by viggo** [enonic/app-siteimprove#37]
We are getting the error: `Siteimprove statistics are not available for "https://bring.no/bring-no".`

The site `bring-no` is inside the folder `bring.no`

Line probably responsible for the issue:

https://github.com/enonic/app-siteimprove/blob/547bbdad6a1c18cea8d012e70e25567c7b39c426/src/main/resources/assets/js/util/SiteimproveValidator.ts#L39

**Comment by viggo** [comment]
I forgot to add that we were running version 1.1.0 of the Siteimprove app. We have now updated to 1.3.1, and the error message is now replaced with blank instead for sites within a folder.

**Comment by alansemenov** [comment]
@viggo We have released a new version (1.3.2) of the app compatible with XP 6.15 (and higher). Please install it and let us know if the issue has been fixed.

**Comment by viggo** [comment]
I have now installed version 1.3.2, and it works as intended. Thank you for the quick resolve! 😃
